name: Deploy to WordPress.org
on:
  push
jobs:
  build:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-dev

      - uses: actions/upload-artifact@v1
        with:
          name: vendor
          path: vendor

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: vendor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: wpcasa-ninja-forms